#!/bin/bash
#PBS -N ez_model_test
#PBS -e out.err                   
#PBS -o out.out
#PBS -l walltime=00:20:00
#PBS -l nodes=1:ppn=9:nogpu
##PBS -l select=1:ncpus=1:nogpu
#PBS -k oe

echo PBS work directory: $PBS_O_WORKDIR

cd $PBS_O_WORKDIR
##cat $PBS_NODEFILE > nodefile
jobid=$(echo $PBS_JOBID | sed 's/.chaos//')
cat $PBS_NODEFILE | uniq > ./mpd_nodefile_$USER$jobid
NP=$(cat $PBS_NODEFILE | wc -l) 

echo Working in $workdir using $NP cores.

cd $workdir

export HDF5_USE_FILE_LOCKING='FALSE'
conda_base="/apps/intel/oneapi/intelpython/latest/"
. $conda_base/etc/profile.d/conda.sh
conda activate general

# Run script
mpirun -np $NP -machinefile $PBS_NODEFILE python3 main_q_parallel.py
